import {z} from  "zod";



// generate bill schema

export const generateBillSchema = z.object({
    patientId:z.string().min(1,"Patient ID is required"),
    appointmentId:z.string().optional(),
    items:z.array(z.objject({
        description:z.string().min(1, "descritpion is required"),
        quantity:z.number().int().min(1,"Quantity must be atleast 1"),
        unitPrice:z.number().positive("unit proice must be  positive number"),
        dicount:z.number().min(0).default(0),
        total:z.number().positive("Total must be positive")
    })),
    tax:z.number().min(0).default(0),
    notes:z.string().max(500,"Notes cannot exceed 500 characters").optional(),
    genratedBy:z.string().min(1,"Generated by is reuired")

})



// update bill schema
export const updateBillSchema = z.object({
    items:z.array(z.object({
        description:z.string().min(1, "descritpion is required"),
        quantity:z.number().int().min(1,"Quantity must be atleast 1"),
        unitPrice:z.number().positive("unit proice must be  positive number"),
        dicount:z.number().min(0).default(0),
        total:z.number().positive("Total must be positive")
    })).optional(),
     tax:z.number().min(0).default(0),
     status:z.enum(['UNPAID', 'PAID',
  'PARTIALLY_PAID',
  'CANCELLED',
  REFUNDED]),
   notes:z.string().max(500,"Notes cannot exceed 500 characters").optional()

})


// get Bills query schema
export const getBillQueryChema = z.object({
    page:z.string().optional().transform(Number).default("1"),
    limit:z.string().optional().transform(Number).default("10"),
    patientId:z.string().optional(),
    status:z.enum(['UNPAID', 'PAID',
  'PARTIALLY_PAID',
  'CANCELLED',
  REFUNDED]),
  fromDate:z.string().datetime().optional(),
  toDate:z.string().datetime().optional(),
  search:z.string().optional(),
})